language: node_js
node_js:
  - "10.19.0"
sudo: required
services:
  - mongodb
  - docker
cache:
  directories:
  - node_modules
git:
  depth: 3
stages:
  - test
  - name: docker
    if: branch = master AND type = push
jobs:
  include:
    - stage: test
      env:
        global:
          - ALGOLIA_APP_ID=algolia_app_id
          - ALGOLIA_API_KEY=algolia_api_key
          - ALGOLIA_POSTS_INDEX=algolia_posts_index
      script:
        - npm run lint
        - npm run test
        - npm run build
    - stage: docker
      script:
        - ./devops/build-api.sh
        - cd devops; ./build-mongodb.sh
